version: "3.8"

services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=walletsdb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: echo-software-take-home
    ports:
      - "8080:8080"
    environment:
      - HOST=localhost
      - PORT=8080
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=walletsdb
      - DB_PORT=5432
      - BASE_URL=https://api.fireblocks.io
    restart: unless-stopped
    depends_on:
      - postgres
